# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=50000
SAVEHIST=50000
setopt appendhistory autocd
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install

# Colors
if [ -x "$(command -v dircolors)" ]; then
   eval `dircolors ~/.dircolors`
fi

# Prompt
#function precmd {
#   # check a4 chroot
#   if ! command -v a4 >/dev/null 2>&1 || [[ -n "${A4_CHROOT}" ]]; then
#      PR_CHROOT_COL="yellow"
#   else
#      PR_CHROOT_COL="blue"
#   fi
#   PR_COL=$PR_CHROOT_COL
#
#   # check ns
#   if [[ -n "${NSNAME}" ]]; then
#      PR_NS=" +${NSNAME}"
#   else
#      PR_NS=""
#   fi
#}
#
## Show vi mode in prompt
#accept-line() { PR_COL=$PR_CHROOT_COL; zle reset-prompt; zle .accept-line }
#zle -N accept-line
#function zle-line-init zle-keymap-select {
#    PR_COL="${${KEYMAP/vicmd/cyan}/(main|viins)/$PR_CHROOT_COL}"
#    zle reset-prompt
#}
#zle -N zle-line-init
#zle -N zle-keymap-select

setprompt () {
   setopt prompt_subst prompt_percent
   autoload -U colors && colors

   PROMPT='%{$fg[$PR_COL]%}%D{%-m/%-d %H:%M}$PR_NS %1d %#%{$reset_color%} '
}

setprompt

fpath=(~/.zsh/completions $fpath)
autoload -U compinit
compinit

# Options
setopt hist_ignore_all_dups inc_append_history hist_save_no_dups hist_reduce_blanks hist_ignore_space
setopt interactivecomments
KEYTIMEOUT=1

# Aliases
alias tt='tmux display-message "Task complete in #S"'
alias vi='vim -u NONE'
alias pb='curl -F c=@- pb'

# Functions

# Environment
export GOPATH=~/go
export PATH=$GOPATH/bin:$PATH
export PATH=$HOME/bin:$PATH
export EDITOR=vim
export P4MERGE=amergeVim
export NOTI_PB=o.xXcIRDklt4berjLHFbbiwOe7f8QjRDml
export TMUX_TMPDIR=$HOME/.tmux/sockets

# Fzf
_gen_fzf_default_opts() {
  local base03="234"
  local base02="235"
  local base01="240"
  local base00="241"
  local base0="244"
  local base1="245"
  local base2="254"
  local base3="230"
  local yellow="136"
  local orange="166"
  local red="160"
  local magenta="125"
  local violet="61"
  local blue="33"
  local cyan="37"
  local green="64"

  # Comment and uncomment below for the light theme.

  ## Solarized Dark color scheme for fzf
  #export FZF_DEFAULT_OPTS="
  #  --color fg:-1,bg:-1,hl:$blue,fg+:$base2,bg+:$base02,hl+:$blue
  #  --color info:$yellow,prompt:$yellow,pointer:$base3,marker:$base3,spinner:$yellow
  #"
  # Solarized Light color scheme for fzf
  export FZF_DEFAULT_OPTS="
    --color fg:-1,bg:-1,hl:$blue,fg+:$base02,bg+:$base2,hl+:$blue,border:$base2
    --color info:$yellow,prompt:$yellow,pointer:$base03,marker:$base03,spinner:$yellow
    --bind alt-p:toggle-preview
  "
}
_gen_fzf_default_opts
export FZF_DEFAULT_COMMAND='rg --files'
export RIPGREP_CONFIG_PATH=~/.ripgreprc

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
